### ISSUE TITLE
Dead Lock on Content Upload

### ISSUE THREAD

**Issue by gerryfletch** [two-app/memory-service#59]
Deadlock found when trying to get lock; try restarting transaction
Encountered when uploading 7 images and 1 video. 

```logs
16:23:26.480 [Server-akka.actor.default-dispatcher-88] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:26.480 [Server-akka.actor.default-dispatcher-88] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:26.494 [ioapp-compute-1] INFO  content.Content - Content type inferred to be Video
16:23:26.494 [ioapp-compute-1] INFO  Compress - Compressing video file.
16:23:26.494 [ioapp-compute-1] INFO  VideoCompression - Compressing video from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0007.MP414072144675736666652.tmp
16:23:26.494 [ioapp-compute-1] INFO  VideoCompression - Extracting file extension of filename: IMG_0007.MP4
16:23:26.494 [ioapp-compute-1] INFO  VideoCompression - Extracting the first frame of the video using ffmpeg.
16:23:26.494 [ioapp-compute-1] INFO  VideoCompression - Generating random prefixed output file with extension 'png'.'
16:23:26.495 [ioapp-compute-1] INFO  VideoCompression - Prepared output file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/0670cc78-c84a-4957-9788-c0738b4e99736367484933442838004.png
16:23:26.495 [ioapp-compute-1] INFO  VideoCompression - Extracting the first frame from video at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0007.MP414072144675736666652.tmp
16:23:26.495 [ioapp-compute-1] INFO  VideoCompression - Storing extracted frame at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/0670cc78-c84a-4957-9788-c0738b4e99736367484933442838004.png
16:23:26.495 [ioapp-compute-1] INFO  VideoCompression - Submitting frame extraction job to ffmpeg executor.
16:23:26.495 [ioapp-compute-1] INFO  net.bramp.ffmpeg.RunProcessFunction - ffmpeg -y -v error -i /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0007.MP414072144675736666652.tmp -vframes 1 /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/0670cc78-c84a-4957-9788-c0738b4e99736367484933442838004.png
16:23:26.580 [Server-akka.actor.default-dispatcher-100] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:26.581 [Server-akka.actor.default-dispatcher-100] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:26.586 [ioapp-compute-2] INFO  content.Content - Content type inferred to be Image
16:23:26.586 [ioapp-compute-2] INFO  Compress - Compressing image file.
16:23:26.586 [ioapp-compute-2] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0001.JPG5771057177498174065.tmp
16:23:26.739 [Server-akka.actor.default-dispatcher-80] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:26.740 [Server-akka.actor.default-dispatcher-80] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:26.748 [ioapp-compute-3] INFO  content.Content - Content type inferred to be Image
16:23:26.749 [ioapp-compute-3] INFO  Compress - Compressing image file.
16:23:26.749 [ioapp-compute-3] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0002.JPG12170177869001203378.tmp
16:23:26.764 [ioapp-compute-1] INFO  VideoCompression - Reading ffmpeg output frame image to file.
16:23:26.765 [ioapp-compute-1] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/0670cc78-c84a-4957-9788-c0738b4e99736367484933442838004.png
16:23:26.786 [ioapp-compute-1] INFO  ImageCompression - Compressing image with original dimensions 568x320.
16:23:26.786 [ioapp-compute-1] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:26.809 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/9aa0f1f1-1eb4-4878-b70f-20c060fc4d0c13477234851350165874.png
16:23:26.810 [ioapp-compute-1] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:26.881 [Server-akka.actor.default-dispatcher-101] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:26.881 [Server-akka.actor.default-dispatcher-101] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:27.078 [ioapp-compute-2] INFO  ImageCompression - Compressing image with original dimensions 2710x1800.
16:23:27.078 [ioapp-compute-2] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:27.168 [ioapp-compute-3] INFO  ImageCompression - Compressing image with original dimensions 2710x1800.
16:23:27.169 [ioapp-compute-3] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:27.361 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/5458740b-16c4-4c86-aa28-a6e8d59533531061626375064655454.png
16:23:27.361 [ioapp-compute-1] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:27.364 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/bd0d3b31-f6d4-429c-b980-6843fbd08a8b2604723431670903038.png
16:23:27.364 [ioapp-compute-2] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:27.389 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/61e7d0d3-39e2-41fd-9b9c-91cd6403f59b9835452545302010710.png
16:23:27.390 [ioapp-compute-3] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:27.445 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/04291ba8-4555-435c-9d32-f7cb61b79e5b8336909847336305540.png
16:23:27.979 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"video","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/13659223-1ff0-4326-9ec2-95caec1d3ea3","gallery":{"contentType":"video","extension":"MP4","suffix":"gallery"},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:27.982 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:27.983 [ioapp-compute-1] INFO  content.Content - Content type inferred to be Image
16:23:27.983 [ioapp-compute-1] INFO  Compress - Compressing image file.
16:23:27.983 [ioapp-compute-1] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0004.JPG16661377208428785226.tmp
16:23:28.084 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/da56f398-0150-429e-95c8-ae8f1780c01c6860240058214700708.png
16:23:28.085 [ioapp-compute-2] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:28.088 [ioapp-compute-1] INFO  ImageCompression - Compressing image with original dimensions 1200x1800.
16:23:28.088 [ioapp-compute-1] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:28.093 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/544ca48c-3756-4b26-837e-adf851b65c037062083216775405852.png
16:23:28.094 [ioapp-compute-3] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:28.161 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/59bb67b7-43e5-43c4-bc4b-9dc5c34f83c714642438400736046283.png
16:23:28.161 [ioapp-compute-1] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:28.558 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/4eee3c31-8ce1-4cb9-b5df-f79f07d25ea14750321725251054616.png
16:23:28.558 [ioapp-compute-1] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:29.762 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/bd6d1abf-c5d7-4cfa-9c11-4d12a3fc742610003356160953507386.png
16:23:30.367 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/3debec0d-20f5-4eea-a856-582df9cc8ec117819785781300804270.png
16:23:30.521 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/1a0c5a22-b319-44f1-a711-a393a95f225b3516243352073053477.png
16:23:31.343 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/80f5bb42-99e2-4dd2-9643-08cc642eb92c","gallery":{"contentType":"image","extension":"png","height":1800,"suffix":"gallery","width":1200},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:31.345 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Connected content id 13 to memory mid 3
16:23:31.348 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:31.349 [Server-akka.actor.default-dispatcher-79] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(13)
16:23:31.353 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Connected content id 14 to memory mid 3
16:23:31.358 [Server-akka.actor.default-dispatcher-103] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(14)
16:23:31.485 [Server-akka.actor.default-dispatcher-79] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:31.486 [Server-akka.actor.default-dispatcher-79] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:31.491 [ioapp-compute-1] INFO  content.Content - Content type inferred to be Image
16:23:31.491 [ioapp-compute-1] INFO  Compress - Compressing image file.
16:23:31.491 [ioapp-compute-1] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0003.JPG16681930948994375395.tmp
16:23:31.568 [Server-akka.actor.default-dispatcher-79] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:31.569 [Server-akka.actor.default-dispatcher-79] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:31.872 [ioapp-compute-1] INFO  ImageCompression - Compressing image with original dimensions 2697x1800.
16:23:31.872 [ioapp-compute-1] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:32.097 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/0e260c94-339e-46a2-a387-8c94680da8bb8241311645864978302.png
16:23:32.097 [ioapp-compute-1] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:32.666 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/6eeae278-a2cb-4944-b6c9-cff2955fa94613600195943625668830.png
16:23:32.666 [ioapp-compute-1] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:33.825 [ioapp-compute-1] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/80e4f494-e4cd-439d-8fe5-19b61f61147412044232796341544018.png
16:23:36.665 [ioapp-compute-2] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/44d525b4-9eaf-4bc3-9a0e-4c02e0237374","gallery":{"contentType":"image","extension":"png","height":1594,"suffix":"gallery","width":2400},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:36.665 [ioapp-compute-3] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/9d73d14d-6f5b-4242-bc56-dee8e4401f5a","gallery":{"contentType":"image","extension":"png","height":1594,"suffix":"gallery","width":2400},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:36.689 [ioapp-compute-3] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:36.689 [ioapp-compute-2] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:36.689 [ioapp-compute-3] INFO  content.Content - Content type inferred to be Image
16:23:36.689 [ioapp-compute-3] INFO  Compress - Compressing image file.
16:23:36.690 [ioapp-compute-3] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0006.HEIC10515073931733647576.tmp
16:23:36.704 [ioapp-compute-2] INFO  content.DoobieContentMetaDao - Connected content id 15 to memory mid 3
16:23:36.711 [Server-akka.actor.default-dispatcher-86] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(15)
[ERROR] [06/30/2020 16:23:36.775] [Server-akka.actor.default-dispatcher-101] [akka.actor.ActorSystemImpl(Server)] Error during processing of request: 'Deadlock found when trying to get lock; try restarting transaction'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5(kleisliinterpreter.scala:958)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5$adapted(kleisliinterpreter.scala:958)
	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:112)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

16:23:36.823 [Server-akka.actor.default-dispatcher-110] INFO  content.ContentRouteDispatcher - POST /memory/3/content.
16:23:36.827 [Server-akka.actor.default-dispatcher-110] INFO  memory.MemoryServiceImpl - Retrieving memory with mid 3 for cid 1
16:23:36.834 [ioapp-compute-2] INFO  content.Content - Content type inferred to be Image
16:23:36.834 [ioapp-compute-2] INFO  Compress - Compressing image file.
16:23:36.834 [ioapp-compute-2] INFO  ImageCompression - Loading image from file at path: /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/IMG_0005.JPG6410326065927325150.tmp
16:23:37.153 [ioapp-compute-3] INFO  ImageCompression - Compressing image with original dimensions 2400x1800.
16:23:37.153 [ioapp-compute-3] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:37.215 [ioapp-compute-2] INFO  ImageCompression - Compressing image with original dimensions 2697x1800.
16:23:37.216 [ioapp-compute-2] INFO  ImageCompression - Generating thumbnail with dimensions 100x100.
16:23:37.333 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/c35670b6-0ab2-4381-8f82-fa245038927b1366357658720976504.png
16:23:37.333 [ioapp-compute-3] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:37.407 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/83deda20-af97-44e5-b8fe-6e1818861d632057316707664977003.png
16:23:37.407 [ioapp-compute-2] INFO  ImageCompression - Generating display with dimensions 400x400
16:23:37.564 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/32d60b85-e891-4f19-ac0b-96871ba3f9db5256353441607496567.png
16:23:37.564 [ioapp-compute-3] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:37.921 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/6b0f9a41-9bbf-41a2-b043-41bdc82d3e2b9527944908896524390.png
16:23:37.921 [ioapp-compute-2] INFO  ImageCompression - Generating gallery with maximum dimensions 2400x2400
16:23:38.834 [ioapp-compute-3] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/57d3be89-25c9-4fd4-b238-740c9a17955c7835989488934471608.png
16:23:39.263 [ioapp-compute-2] INFO  ImageCompression - Writing compressed file to path /var/folders/j_/jx4hdxs53w15msj26ffkbj4c0000gn/T/49c91de1-a476-4fe3-80c2-03636ffca65c6669787557688954470.png
16:23:39.502 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/03b909e8-3bee-4d5d-bbfe-fba7b02e2578","gallery":{"contentType":"image","extension":"png","height":1601,"suffix":"gallery","width":2400},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:39.506 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:39.508 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Connected content id 17 to memory mid 3
16:23:39.510 [Server-akka.actor.default-dispatcher-110] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(17)
16:23:44.117 [ioapp-compute-2] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/445f19be-57dd-4201-9b2a-57343506dd9b","gallery":{"contentType":"image","extension":"png","height":1601,"suffix":"gallery","width":2400},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:44.121 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:44.126 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Connected content id 18 to memory mid 3
16:23:44.128 [Server-akka.actor.default-dispatcher-100] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(18)
16:23:44.995 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Storing content metadata against mid 3: {"contentId":-1,"contentType":"image","display":{"contentType":"image","extension":"png","height":400,"suffix":"display","width":400},"fileKey":"memory/3/7487f4d9-a406-43d3-97bf-78cc1fcbd1b4","gallery":{"contentType":"image","extension":"png","height":1800,"suffix":"gallery","width":2400},"thumbnail":{"contentType":"image","extension":"png","height":100,"suffix":"thumbnail","width":100}}
16:23:44.998 [ioapp-compute-1] INFO  content.DoobieContentMetaDao - Inserted metadata generating content id $contentId
16:23:45.001 [ioapp-compute-2] INFO  content.DoobieContentMetaDao - Connected content id 19 to memory mid 3
16:23:45.004 [Server-akka.actor.default-dispatcher-79] INFO  content.ContentRouteDispatcher - Completing with result: ContentUploadResponse(19)
```

**Comment by gerryfletch** [comment]
This seems to be caused by two transactions running at the exact same time (to the millisecond) which require locking a memory to update the display content ID. 

This will be removed by this feature: https://github.com/two-app/two-app/issues/93 so it is not worth writing a fix for it.
